### ISSUE TITLE
`fn`s don't quite work!

### ISSUE THREAD

**Issue by KDPRoss** [dball/jolips#1]
Now that I've actually met you ... Try something like `(((fn (x) (fn (y) (+ x y))) 2) 3)` ... Happy to discuss ... but wanted to give you a chance to investigate / think it through :~} (Stephen mentioned that you'd done this project, so I had to take a look! ... Happy to contribute a crappy top-level interactive REPL that I tossed together to try it out, if you like.)

**Comment by dball** [comment]
Thanks for the observation and failing test case! I believe it's corrected by 19bbdade545f59fa439854b1d8ccf1401c7fd3ba
